In [38]:
import json
import numpy as np

In [39]:
json_file = open("example-2layer.json", "r") # open json file in reading mode
data = json.load(json_file) # load json file in datastructure with json

In [40]:
matrices = [] # empty list for all matrices
for layer in data: # iterate over layers in json file
    
    matrix = np.zeros([int(data[layer]["size_out"]), int(data[layer]["size_in"])], dtype = float) # create empty matrix

    for index, node in enumerate(data[layer]["weights"]): # iterate over nodes in layer

        for weight in data[layer]["weights"][node]: # iterate over weights in node
            
            matrix[int(weight) - 1][int(node) - 1] = float(data[layer]["weights"][node][weight])
            # add weight to correct place in matrix
            
    matrices.append(matrix) # add matrix to all matrices

In [41]:
matrixinput = np.matrix([[1]] * int(data["layer1"]["size_in"])) # input matrix for the neural network

In [42]:
for layer, matrix in enumerate(reversed(matrices)): # iterate over matrices
    print("Matrix "+str(layer + 1)+":\n"+str(matrix)+'\n') # print matrix
    
    if len(matrices) == 1:
        matrixvar = matrixinput
    if layer + 1 == len(matrices):
        matrix = matrix_dot_result
        matrixvar = matrixinput
        print("All matrices multiplied:\n"+str(matrix)) # print matrix
        print("Multiplied with input:\n"+str(matrixvar)+'\n') # print matrix
    else:
        matrixvar = matrices[layer]

    matrix_dot_result = np.zeros([len(matrix), len(matrixvar[0])], dtype = float) # create new empty matrix
    
    for irow, row in enumerate(matrix): # iterate over rows in matrix
        
        for i in range(0, len(matrixvar[0])): # iterate over number of columns in matrixvar
            sum = 0
        
            for iweight, weight in enumerate(row): # iterate over weights in row
                sum += matrix[irow][iweight] * matrixvar[iweight][i] # add sum of muliplied weights to variable sum 
            
            matrix_dot_result[irow][i] = sum # add sum to correct place in newmatrix
    
print("Output values:\n", matrix_dot_result) # print output

Matrix 1:
[[ 0.5  0.2 -0.1  0.9]
 [ 0.2 -0.5  0.3  0.1]]

Matrix 2:
[[ 0.5  0.2  0.   0.  -0.2]
 [ 0.2 -0.5 -0.1  0.9 -0.8]
 [ 0.   0.2  0.   0.1 -0.1]
 [ 0.1  0.8  0.3  0.  -0.7]]

All matrices multiplied:
[[ 0.38  0.7   0.25  0.17 -0.88]
 [ 0.01  0.43  0.08 -0.42  0.26]]
Multiplied with input:
[[1]
 [1]
 [1]
 [1]
 [1]]

Output values:
 [[0.62]
 [0.36]]
