In [13]:
import json
import numpy as np

In [14]:
json_file = open("example-2layer.json", "r") # open json file in reading mode
data = json.load(json_file) # load json file in datastructure with json

In [15]:
matrices = [] # empty list for all matrices
for layer in data: # iterate over layers in json file
    
    matrix = np.zeros([int(data[layer]["size_in"]), int(data[layer]["size_out"])], dtype = float) # create empty matrix

    for index, node in enumerate(data[layer]["weights"]): # iterate over nodes in layer

        for weight in data[layer]["weights"][node]: # iterate over weights in node
            
            matrix[int(node) - 1][int(weight) - 1] = float(data[layer]["weights"][node][weight])
            # add weight to correct place in matrix
            
    matrices.append(matrix) # add matrix to all matrices

In [16]:
for layer, matrix in enumerate(matrices): # iterate over matrices
    print("Matrix "+str(layer + 1)+":\n"+str(matrix)+'\n') # print current matrix
    
    if layer == 0:
        matrix = [[1,1,1,1,1]]#np.matrix([1] * int(data["layer1"]["size_in"])) # input matrix for the neural network
        matrixvar = matrices[layer]
    else:
        matrix = matrix_dot_result
        matrixvar = matrices[layer]
        
    if len(matrix[0]) == len(matrixvar):
        matrix_dot_result = np.zeros([len(matrix), len(matrixvar[0])], dtype = float) # create new empty matrix
    else:
        print("dot product not possible")
    
    for irow, row in enumerate(matrix): # iterate over rows in matrix
        
        for i in range(0, len(matrixvar[0])): # iterate over number of columns in matrixvar
            sum = 0
        
            for iweight, weight in enumerate(row): # iterate over weights in row
                sum += matrix[irow][iweight] * matrixvar[iweight][i] # add sum of muliplied weights to variable sum 
            
            matrix_dot_result[irow][i] = sum # add sum to correct place in newmatrix

    print(matrix_dot_result)
    
print("Last output values:\n", matrix_dot_result) # print last matrix

Matrix 1:
[[ 0.5  0.2  0.   0.1]
 [ 0.2 -0.5  0.2  0.8]
 [ 0.  -0.1  0.   0.3]
 [ 0.   0.9  0.1  0. ]
 [-0.2 -0.8 -0.1 -0.7]]

[[ 0.5 -0.3  0.2  0.5]]
Matrix 2:
[[ 0.5  0.2]
 [ 0.2 -0.5]
 [-0.1  0.3]
 [ 0.9  0.1]]

[[0.62 0.36]]
Last output values:
 [[0.62 0.36]]


In [ ]:
[[ 0.38  0.01]
 [ 0.7   0.43]
 [ 0.25  0.08]
 [ 0.17 -0.42]
 [-0.88  0.26]]

Dit is de output matrix met dimensie 5x2, voor multiplicatie Matrix laag 1 (5x4) en 2 (4x2).